### ISSUE TITLE
Schemer muss prüfen, ob Basisvariable mit abgeleiteter Variable kollidiert

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/coding-components#26]
Sollte nachträglich in der Variablenliste (Basisvariablen) eine ID auftauchen, zu der es schon eine abgeleitete Variable existiert, bekommt der Schemer das nicht mit und dann gibt es beim Autocoder ein Problem.

**Comment by jurei733** [comment]
Folgenden Ablauf würde ich vorschlagen:
1) Prüfen beim Abruf der Basisvariablen Liste vom Editor ob es eine gleichnamige abgeleitete Variable gibt.
2) Falls ja: Ignoriere die Basisvariable und behalte abgeleitete Variable
    Falls nein: Übernehme die Basisvariable

**Comment by jurei733** [comment]
In den Responses werden alle Variablen geschickt und dadurch kommt es zur Kollision mit abgleiteten Variablen aus dem Kodierschema mit gleichlautender Id.
