### ISSUE TITLE
CMC, MC mit Bildern

### ISSUE THREAD

**Issue by franikowsp** [iqb-berlin/coding-components#5]
Bei diesem [Beispiel](https://www.iqb-studio.de/#/a/325/6245/preview) sollte das dritte Bild den Code `1` "Richtig" ausgeben und zu einer Bewertung `1` führen. Keine der Optionen führt zu diesem Ereignis.

Gewählt wurde als Bedingung: "Zeichen/Text: Übereinstimmung" und der Abgleichswert `3`.

Analoges gilt für diese CMC-Aufgabe (Ableitung daher auch falsch): https://www.iqb-studio.de/#/a/325/23831/preview

Muster wäre eigentlich `1`-`2`-`1`

**Comment by jurei733** [comment]
Hier ist durch das generieren mit Kodiermodell "Auswahl/Ankreuzen" die Kodierung korrupt und durch das Löschen der Codes und erstellen mit anderem Kodiermodell entsteht eine gültige Kodierung mit korrekter Ableitung.

Bei der zweiten Aufgabe verhält es sich ebenso.
Nach dem neu anlegen aller Codes einschließlich der Codes der abgeleiten Variable ist die Kodierung korrekt.
