### ISSUE TITLE
Numerische Kurzantworten

### ISSUE THREAD

**Issue by franikowsp** [iqb-berlin/coding-components#6]
Bei diesem [Beispiel](https://www.iqb-studio.de/#/a/325/13479/preview) sollte die Zahl 49 den Code `1` "Richtig" ausgeben und zu einer Bewertung `1` führen, was aktuell nicht der Fall ist.

Gewählt wurde als Bedingung: "Numerisch: Übereinstimmung" und der Abgleichswert `49`.

**Comment by jurei733** [comment]
Mit der Funktion "Generierung von Code"  --> Setzen der Checkbox "Soll der Wert als Zahl interpretiert werden?" (Kodiermodell "Zahl") wird aktuell keine gültige Kodierung erzeugt. Kurzfristig lässt es sich lösen indem der "Richtig Code" erst gelöscht und dann identisch neu erzeugt wird oder die Checkbox "Soll der Wert als Zahl interpretiert werden?" nicht gesetzt wird und das Kodiermodell "Wortliste" zur Anwendung kommt. Eine weitere Möglichkeit besteht darin ohne Kodiermodell diesselben Codes zu erstellen wobei dann ebenfalls ein gültige Kodierung entsteht.
