### ISSUE TITLE
Durchstreichen

### ISSUE THREAD

**Issue by franikowsp** [iqb-berlin/coding-components#7]
Bei diesem [Beispiel](https://www.iqb-studio.de/#/a/357/49664/preview) (Achtung - könnte bald verschoben werden!) sollten die Optionen `2` und `1` den Code `1` "Richtig" ausgeben und zu einer Bewertung `1` führen, was aktuell nicht der Fall ist. Die Ableitung ist daher ebenfalls nicht erfolgreich.

Gewählt wurde als Bedingung: "Zeichen/Text: Übereinstimmung" und die entsprechenden Abgleichswerte.

**Comment by jurei733** [comment]
Der Player Response gibt aktuell für das Durchstreich Element als Value den Wert des Durchgestrichenen Elementes zurück. Ist das Durchgestrichene Wort oben dann wird der Wert 1 zurückgegeben. Der "Richtig" Code ist dann entsprechend dieser Wert. Ist zwar nicht ganz inituitiv aber so dann korrekt. Außerdem wurde die Kodierung hier wieder automatisch generiert was momentan für "Auswahl/Ankreuzen" kein valide Kodierung liefert. Hier dann kurzfristig ohne Kodiermodell arbeiten.
